name: build test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-15
          - windows-2022
        python-version:
          - '3.12'
    steps:
      - name: 'Install Packages'
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -yq x11-utils libxkbcommon-x11-0 libfuse2t64
          elif [ "${{ runner.os }}" == "macOS" ]; then
            brew install create-dmg
          elif [ "${{ runner.os }}" == "Windows" ]; then
            echo "Noting to install on windows"
          else
            echo "${{ runner.os }} not supported"
            exit 1
          fi
        shell: bash
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python -m pip freeze
      - run: python3 pack.py || python pack.py
      - name: 'List build output'
        run: ls -l dist
        shell: bash
